export const LiveEventsTypes = {
  FETCH_LIVE_EVENTS_REQUEST: 'FETCH_LIVE_EVENTS_REQUEST',
  FETCH_LIVE_EVENTS_SUCCESS: 'FETCH_LIVE_EVENTS_SUCCESS',
  FETCH_LIVE_EVENTS_FAILURE: 'FETCH_LIVE_EVENTS_FAILURE',
};
